/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	echo_v1alpha1 "github.com/objectrocket/tiny-operator/pkg/apis/echo/v1alpha1"
	versioned "github.com/objectrocket/tiny-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/objectrocket/tiny-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/objectrocket/tiny-operator/pkg/client/listers/echo/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// EchoServerInformer provides access to a shared informer and lister for
// EchoServers.
type EchoServerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.EchoServerLister
}

type echoServerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewEchoServerInformer constructs a new informer for EchoServer type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEchoServerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEchoServerInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredEchoServerInformer constructs a new informer for EchoServer type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEchoServerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EchoV1alpha1().EchoServers(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EchoV1alpha1().EchoServers(namespace).Watch(options)
			},
		},
		&echo_v1alpha1.EchoServer{},
		resyncPeriod,
		indexers,
	)
}

func (f *echoServerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEchoServerInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *echoServerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&echo_v1alpha1.EchoServer{}, f.defaultInformer)
}

func (f *echoServerInformer) Lister() v1alpha1.EchoServerLister {
	return v1alpha1.NewEchoServerLister(f.Informer().GetIndexer())
}
