/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/objectrocket/tiny-operator/pkg/apis/echo/v1alpha1"
	scheme "github.com/objectrocket/tiny-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EchoServersGetter has a method to return a EchoServerInterface.
// A group's client should implement this interface.
type EchoServersGetter interface {
	EchoServers(namespace string) EchoServerInterface
}

// EchoServerInterface has methods to work with EchoServer resources.
type EchoServerInterface interface {
	Create(*v1alpha1.EchoServer) (*v1alpha1.EchoServer, error)
	Update(*v1alpha1.EchoServer) (*v1alpha1.EchoServer, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.EchoServer, error)
	List(opts v1.ListOptions) (*v1alpha1.EchoServerList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.EchoServer, err error)
	EchoServerExpansion
}

// echoServers implements EchoServerInterface
type echoServers struct {
	client rest.Interface
	ns     string
}

// newEchoServers returns a EchoServers
func newEchoServers(c *EchoV1alpha1Client, namespace string) *echoServers {
	return &echoServers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the echoServer, and returns the corresponding echoServer object, and an error if there is any.
func (c *echoServers) Get(name string, options v1.GetOptions) (result *v1alpha1.EchoServer, err error) {
	result = &v1alpha1.EchoServer{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("echoservers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EchoServers that match those selectors.
func (c *echoServers) List(opts v1.ListOptions) (result *v1alpha1.EchoServerList, err error) {
	result = &v1alpha1.EchoServerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("echoservers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested echoServers.
func (c *echoServers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("echoservers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a echoServer and creates it.  Returns the server's representation of the echoServer, and an error, if there is any.
func (c *echoServers) Create(echoServer *v1alpha1.EchoServer) (result *v1alpha1.EchoServer, err error) {
	result = &v1alpha1.EchoServer{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("echoservers").
		Body(echoServer).
		Do().
		Into(result)
	return
}

// Update takes the representation of a echoServer and updates it. Returns the server's representation of the echoServer, and an error, if there is any.
func (c *echoServers) Update(echoServer *v1alpha1.EchoServer) (result *v1alpha1.EchoServer, err error) {
	result = &v1alpha1.EchoServer{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("echoservers").
		Name(echoServer.Name).
		Body(echoServer).
		Do().
		Into(result)
	return
}

// Delete takes name of the echoServer and deletes it. Returns an error if one occurs.
func (c *echoServers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("echoservers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *echoServers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("echoservers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched echoServer.
func (c *echoServers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.EchoServer, err error) {
	result = &v1alpha1.EchoServer{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("echoservers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
